apiVersion: v1
kind: Pod
metadata: # name의 경우 고유해야 하므로 다른 사용자의 자원들과 이름이 겹쳐서는 안 됨
  name: sangminnim-dacon # "사용자명-프로젝트명" 형식으로 작성. 예시: jungin500-yolox
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 1003

  restartPolicy: OnFailure

  volumes:
    - name: shmdir
      emptyDir:
        medium: Memory
    - name: pvc-volume
      persistentVolumeClaim:
        claimName: lab-pvc

  containers:
    - name: gpu-container
      image: ost-hub:5000/nvidia/pytorch:22.02-py3 # 이미지 변경 (nvcr.io/nvidia/pytorch:22.02-py3 등)
      volumeMounts:
        - mountPath: /dev/shm
          name: shmdir
        - mountPath: /home/lab
          name: pvc-volume
      command:
        - "/bin/sh"
        - "-c"
      args: # 컨테이너 내에서 실행될 명령어. 직접 SSH로 접속하는 작업도 가능하나 코드를 미리 작성해두고 1회성 학습에 사용하는 것이 바람직험.
        - >-
          set -x &&
          groupadd -g 1003 lab &&
          useradd -m -d /workspace -s /bin/bash -u 1003 -g lab lab &&
          # runuser -u lab -- git clone https://github.com/jungin500/rexnet --branch jungin500 rexnet &&
          # cd /workspace/rexnet &&
          runuser -u lab -- pip3 install -r requirements.txt &&
          runuser -u lab -- python train.py --manualSeed 7 --saved_model saved_models/TPS-VGG-BiLSTM-Attn-Seed5/best_norm_ED.pth --FT --batch_size 32 --imgH 500 --imgW 160 --train_data train_lmdb_dataset --valid_data val_lmdb_dataset --num_iter 500000 --valInterval 1000 --select_data basic --batch_ratio 1.0 --batch_max_length 30 --data_filtering_off --Transformation TPS --FeatureExtraction VGG --SequenceModeling BiLSTM --Prediction Attn;

      securityContext:
        allowPrivilegeEscalation: false

      resources:
        requests:
          nvidia.com/gpu: 1
        limits:
          nvidia.com/gpu: 1
